modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CreativeMD/AmbientSounds/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="ambientsounds"
    logoFile="ambientsounds.png"
    version="5.0.16"
    displayName="AmbientSounds"
    displayURL="https://modrinth.com/mod/ambientsounds"
    displayTest="IGNORE_SERVER_VERSION"
    authors="CreativeMD"
    description='''Expands minecraft's ambient sounds.'''

[[dependencies.ambientsounds]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambientsounds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ambientsounds]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="[2.11.27,)"

